export const draftExcuses = [
  "Sorry, I have therapy at 3",
  "I'm on antidepressants, legally unhinged",
  "My screen time is 14 hours/day, I'd be a liability",
  "I identify as a conscientious objector to mornings",
  "I have a Duolingo streak to maintain",
  "My emotional support water bottle doesn't fit in a tank",
  "I can't — Mercury is in retrograde",
  "I'm built different (derogatory)",
  "I have carpal tunnel from doomscrolling",
  "My therapist said no",
  "I'd have to cancel my Spotify Premium",
  "I'm allergic to conflict that isn't on Twitter",
  "Can't run in platforms, bestie",
  "I still don't know how to do taxes, you trust me with a weapon?",
  "I need my 8-step skincare routine or I literally combust",
  "I have a very important Zoom meeting that day",
  "My astrologer said this wasn't in my chart",
  "I'm too anxious to commit to plans, let alone a war",
  "Sorry, my Apple Watch says I need to breathe",
  "I only fight in the comments section",
  "I'm vegan, I can't handle that much aggression",
  "My crystals said no",
  "I'd rather unalive my WiFi than myself",
  "I have a TikTok to post at 7pm, it's scheduled",
  "I can't be in trenches — I have scoliosis from my posture",
  "I'm already fighting a war with my landlord",
  "Bold of you to assume I can wake up before noon",
  "I only do violence in Fortnite",
  "My SHEIN order is arriving Thursday, I need to be home",
  "I literally cannot function without oat milk",
];

export const outfitPieces = {
  head: [
    { name: "Tactical Beret", emoji: "🎖️", vibe: "+10 Main Character Energy" },
    { name: "AirPods Max", emoji: "🎧", vibe: "+15 Noise Cancelling War" },
    { name: "Bucket Hat (Camo)", emoji: "🪖", vibe: "+5 Stealth Mode" },
    { name: "Cat Ears Headband", emoji: "😺", vibe: "+20 Psychological Warfare" },
    { name: "Balenciaga Helmet", emoji: "⛑️", vibe: "+25 Combat Couture" },
    { name: "Tinfoil Hat", emoji: "🔮", vibe: "+30 Conspiracy Core" },
  ],
  top: [
    { name: "Cropped Camo Jacket", emoji: "🧥", vibe: "+15 Tactical But Make It Fashion" },
    { name: "Oversized Band Tee", emoji: "👕", vibe: "+10 Draft Day Casual" },
    { name: "Bulletproof Corset", emoji: "🦺", vibe: "+30 War Couture" },
    { name: "Hawaiian Shirt", emoji: "🌺", vibe: "+20 Chaos Energy" },
    { name: "\"I'm With Stupid →\" Tee", emoji: "👕", vibe: "+25 Morale Damage" },
    { name: "Puffer Vest (Neon)", emoji: "🧥", vibe: "+10 Trench Drip" },
  ],
  bottom: [
    { name: "Cargo Pants (Low Rise)", emoji: "👖", vibe: "+15 Utility Chic" },
    { name: "Camo Mini Skirt", emoji: "👗", vibe: "+20 Serving in Every Way" },
    { name: "Sweatpants", emoji: "🩳", vibe: "+5 Drafted But Not Dressed" },
    { name: "Leather Pants", emoji: "👖", vibe: "+25 Apocalypse Glam" },
    { name: "Pajama Bottoms", emoji: "😴", vibe: "+0 I Refuse" },
    { name: "Tactical Kilt", emoji: "🏴", vibe: "+30 Psychological Warfare" },
  ],
  feet: [
    { name: "Combat Boots (Platform)", emoji: "🥾", vibe: "+20 Tall in the Trenches" },
    { name: "Crocs (Sport Mode)", emoji: "🐊", vibe: "+15 Always Battle Ready" },
    { name: "Nike Air Max", emoji: "👟", vibe: "+10 Running From Problems" },
    { name: "Barefoot", emoji: "🦶", vibe: "+0 Feral Mode Activated" },
    { name: "Heeled Boots", emoji: "👢", vibe: "+25 Slay (Literally)" },
    { name: "Uggs", emoji: "🧸", vibe: "+5 Comfort in Chaos" },
  ],
  accessory: [
    { name: "Stanley Cup", emoji: "🥤", vibe: "+10 Hydrated & Dangerous" },
    { name: "Emotional Support Tote Bag", emoji: "👜", vibe: "+15 Carrying Trauma" },
    { name: "Ring Light", emoji: "💡", vibe: "+20 Content in the Crossfire" },
    { name: "Crystals & Sage", emoji: "🔮", vibe: "+25 Spiritual Warfare" },
    { name: "Portable Charger", emoji: "🔋", vibe: "+30 Can't Die, Phone at 5%" },
    { name: "Disposable Camera", emoji: "📸", vibe: "+15 War but Aesthetic" },
  ],
};

export const bingoItems = [
  "Someone plays Fortunate Son unironically",
  "\"Will this affect my Uber Eats?\"",
  "TikTok war correspondent",
  "Someone brings a ring light to the trench",
  "\"Can I bring my cat?\"",
  "Group chat renamed to \"Squad (literal)\"",
  "Someone asks for the WiFi password",
  "\"Is there vegan MRE?\"",
  "Emotional support grenade",
  "Someone does a fit check in camo",
  "\"My therapist is gonna hear about this\"",
  "Draft letter used as TikTok prop",
  "Someone manifests peace",
  "\"This is giving... war crimes\"",
  "Astrology used for battle strategy",
  "Someone reviews the trench on Yelp",
  "\"Wait, there's no AC?\"",
  "Side parting the helmet hair",
  "Someone starts a podcast from the bunker",
  "\"Can I expense this?\"",
  "Free space: existential crisis",
  "Someone asks ChatGPT for battle plans",
  "\"Is this tax deductible?\"",
  "Wellness check from the battlefield",
  "Someone brings a yoga mat to camp",
];

export const survivalQuestions = [
  {
    question: "How's your screen time?",
    options: [
      { text: "Under 2 hours", score: 10 },
      { text: "4-8 hours", score: 5 },
      { text: "I am the screen", score: 2 },
      { text: "My phone IS my personality", score: 0 },
    ],
  },
  {
    question: "Can you run a mile?",
    options: [
      { text: "Easily", score: 10 },
      { text: "Only if chased", score: 6 },
      { text: "Only to the fridge", score: 3 },
      { text: "I get winded opening jars", score: 1 },
    ],
  },
  {
    question: "What's your main skill?",
    options: [
      { text: "Survival instincts", score: 10 },
      { text: "Meme creation under pressure", score: 7 },
      { text: "Making a mean oat milk latte", score: 4 },
      { text: "Crying", score: 2 },
    ],
  },
  {
    question: "How do you handle conflict?",
    options: [
      { text: "Head on, assertively", score: 10 },
      { text: "Passive-aggressive Instagram story", score: 5 },
      { text: "Ghost them", score: 3 },
      { text: "Subtweet and block", score: 1 },
    ],
  },
  {
    question: "What are you bringing to the battlefield?",
    options: [
      { text: "First aid kit", score: 10 },
      { text: "Portable charger", score: 6 },
      { text: "Emotional baggage", score: 3 },
      { text: "My Squishmallow collection", score: 1 },
    ],
  },
  {
    question: "What's your wake-up time?",
    options: [
      { text: "5 AM, no alarm needed", score: 10 },
      { text: "8 AM with 7 alarms", score: 6 },
      { text: "Noon on a good day", score: 3 },
      { text: "I haven't slept since 2019", score: 1 },
    ],
  },
];

export const survivalRatings = [
  { min: 0, max: 15, title: "Certified Cooked", desc: "You'd get lost going to the mess hall. But your meme game might save morale. Maybe.", emoji: "💀" },
  { min: 16, max: 30, title: "Canon Fodder with Rizz", desc: "You'd vlog your way through basic training and go viral. Survival? Unlikely. Clout? Guaranteed.", emoji: "📱" },
  { min: 31, max: 45, title: "Tactical Girlie", desc: "You'd somehow negotiate a ceasefire using astrology and a mood board. Chaotic but effective.", emoji: "✨" },
  { min: 46, max: 60, title: "Main Character of WW3", desc: "Plot armor is THICK. You'd accidentally stumble into being a war hero while looking for the WiFi.", emoji: "🎬" },
];

export const tickerHeadlines = [
  "BREAKING: Gen Z soldier refuses to leave trench until WiFi password is provided",
  "DEVELOPING: Entire battalion late to deployment — alarm was on vibrate",
  "URGENT: Soldier caught doing skincare routine during ambush, claims \"self-care isn't selfish\"",
  "UPDATE: Military replaces bugle with iPhone alarm — troops still hitting snooze",
  "BREAKING: Private asks drill sergeant to use their preferred pronouns mid-pushup",
  "LIVE: Troops demand plant-based MREs and gluten-free grenades",
  "DEVELOPING: Gen Z soldier rates trenches 2 stars on Google — \"no outlets\"",
  "ALERT: Combat mission delayed 40 min — troops needed to charge AirPods",
  "BREAKING: Soldier goes AWOL to maintain 365-day Duolingo streak",
  "UPDATE: Gen Z negotiates ceasefire through group chat — \"we literally can't even\"",
  "URGENT: Supply drop contains Stanley cups instead of ammunition",
  "LIVE: Private starts GoFundMe for \"emotional support tank\"",
  "BREAKING: Battlefield meditation circle causes confusion among enemy forces",
  "DEVELOPING: Soldier submits PTO request for mental health day during siege",
  "ALERT: Entire platoon refuses to march without curated Spotify playlist",
  "UPDATE: WW3 paused — both sides watching the same Netflix show, no spoilers policy in effect",
  "BREAKING: Soldier asks commanding officer \"is this giving Geneva Convention?\"",
  "LIVE: TikTok creator hits 1M followers from frontline — gets brand deal with camo brand",
  "URGENT: Troops demand avocado toast in mess hall or they're \"literally done\"",
  "DEVELOPING: Gen Z soldier hacks enemy comms using only an iPad and spite",
];
